### ISSUE TITLE
using viewBox causes calculations to be off

### ISSUE THREAD

**Issue by derricksimpson** [danny-toi/Snap.svg.FreeTransform#6]
While using a viewBox="width height" to scale my content, problems are created for the FreeTransform class where the outline rects are larger than the content.  IT seems that some of the components scale correctly, but some do not.

I think you'll need to calculate a multiplier based on the original SVG size vs the scaled Size and use this in the calculations for rendering the components.

Thanks!

**Comment by markskayff** [comment]
Let me tell you there's a guy who forked this project and is maintaining it more actively. He solved many of these issues. 

Here is the repo: https://github.com/ibrierley/Snap.svg.FreeTransform

**Comment by derricksimpson** [comment]
Got it. Thanks for your work on this, and thanks for letting me know.

Regards

**Comment by markskayff** [comment]
Yes, well, I'm not the owner of the project. I'm just someone participating and using it actively here.

**Comment by derricksimpson** [comment]
seems abandoned. :(
